packages:
  - examples/**
  - packages/**
  - '!**/test/**'
onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@nestjs/core'
  - '@swc/core'
  - esbuild
catalog:
  vite: ^7.0.0
  '@types/node': ^20.0.0
  '@nestjs/common': ^11.0.0
